### ISSUE TITLE
Doodle poll to set the time for the next meeting

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [codeforamerica/cross-brigade-collab#4]
### Overview
We need a doodle poll to get the people who want to be in this meeting for the next one to set a time.

### Action Items
- [x] Create a Doodle poll for time and dates set in the comments
- [ ] invite previous attendees and post in general as well
- [x] delete links to old doodle poll in the pins

**Comment by ExperimentsInHonesty** [comment]
Current doodle poll is short term (2 weeks from today - 7/13 and 7/14) (3 - 6pm PST slots)

**Comment by ExperimentsInHonesty** [comment]
Current Doodle that Peter Dudka created https://doodle.com/poll/ahs4khn2f2sgrfs5

**Comment by plocket** [comment]
Closing issue because new poll is needed. Will add dates to doodle poll issues.
